version: '3.8'
services:
  risks:
    image: mzegarra/ms-risks-sg:1.0.0
    platform: linux/amd64
    build:
      context: ./ms-risk
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "9062:9062"
  customers:
    image: mzegarra/ms-customers-sg:1.0.1
    platform: linux/amd64
    build:
      context: ./ms-customers
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "9060:9060"
  accounts:
    image: mzegarra/ms-accounts-sg:1.0.2
    platform: linux/amd64
    build:
      context: ./ms-accounts
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "9061:9061"
  accounts-graphql:
    image: mzegarra/ms-accounts-graphql-sg:1.0.9
    platform: linux/amd64
    build:
      context: ./ms-accounts-graphql
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MSACCOUNTS_URL=http://accounts:9061/
  customers-graphql:
    image: mzegarra/ms-customers-graphql-sg:1.0.2
    platform: linux/amd64
    build:
      context: ./ms-customers-graphql
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MSCUSTOMERS_URL=http://customers:9060/
  risks-graphql:
    image: mzegarra/ms-risks-graphql-sg:1.0.1
    platform: linux/amd64
    build:
      context: ./ms-risks-graphql
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MSCUSTOMERS_URL=http://risks:9062/
