#spring:
#  jackson:
#    date-format: "YYYY-MM-dd"
#    serialization:
#      write_dates_as_timestamps: false
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  r2dbc.url: r2dbc:h2:file:///./testdb2
#server:
#  port: 9061


#microservices.customers:
#  url: ${MSCUSTOMERS_URL:http://localhost:9060/}

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/customers_db?schema=accounts_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    properties:
      schema: accounts_schema

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

