
microservices.customers:
  url: ${MSCUSTOMERS_URL:http://localhost:9060/}


dgs:
  graphql:
    schema-location:
      - "classpath*:schema/**/*.graphql*"
      - "classpath*:schema/**/*.gql"

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

